#pragma once

enum class RoadType { ROAD, RAIL, AIR, WATER };
enum class RoadCharacteristic { HIGHWAY, CITY_STREET, DIRT_ROAD, PARK_ROAD, STANDARD, DENSELY_POPULATED_CITY };
enum class ObstacleCause { TRAFFIC_JAM, ACCIDENT, CONSTRUCTION, WEATHER_HEAVY_RAIN, WEATHER_SNOW, WEATHER_WIND, CUSTOM_DELAY };
enum class ObstacleImpact { ALL_VEHICLES, ROAD_ONLY, RAIL_ONLY, AIR_ONLY, WATER_ONLY };